<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="15.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup>
    <MSBuildAllProjects>$(MSBuildAllProjects);$(MSBuildThisFileFullPath)</MSBuildAllProjects>
    <_TinyCLRUsbHostImplSource>$(MSBuildThisFileDirectory)..\..\lib\net48\GHIElectronics.TinyCLR.Devices.UsbHost.dll</_TinyCLRUsbHostImplSource>
  </PropertyGroup>
  <Target Name="CopyTinyCLRUsbHostImplForDebugger" AfterTargets="AfterBuild" Condition="Exists('$(_TinyCLRUsbHostImplSource)')">
    <Copy SourceFiles="$(_TinyCLRUsbHostImplSource)" DestinationFiles="$(OutDir)pe\GHIElectronics.TinyCLR.Devices.UsbHost.dll" OverwriteReadOnlyFiles="true" SkipUnchangedFiles="false" />
  </Target>
</Project>
