<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="15.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <ItemGroup>
    <Reference Include="GHIElectronics.TinyCLR.Collections" Condition="'$(NuGetProjectStyle)' != 'PackageReference'">
      <HintPath>$(MSBuildThisFileDirectory)..\..\lib\net48\GHIElectronics.TinyCLR.Collections.dll</HintPath>
      <Private>False</Private>
    </Reference>
  </ItemGroup>
  <PropertyGroup>
    <MSBuildAllProjects>$(MSBuildAllProjects);$(MSBuildThisFileFullPath)</MSBuildAllProjects>
    <_TinyCLRCollectionsShimSource>$(MSBuildThisFileDirectory)..\..\desktop-shim\GHIElectronics.TinyCLR.Collections.dll</_TinyCLRCollectionsShimSource>
    <_TinyCLRCollectionsImplSource>$(MSBuildThisFileDirectory)..\..\tinyclr\GHIElectronics.TinyCLR.Collections.dll</_TinyCLRCollectionsImplSource>
  </PropertyGroup>
  <Target Name="CopyTinyCLRCollectionsDesktopShim" AfterTargets="AfterBuild" Condition="Exists('$(_TinyCLRCollectionsShimSource)')">
    <Copy SourceFiles="$(_TinyCLRCollectionsShimSource)" DestinationFiles="$(OutDir)GHIElectronics.TinyCLR.Collections.dll" OverwriteReadOnlyFiles="true" SkipUnchangedFiles="false" />
  </Target>
  <Target Name="CopyTinyCLRCollectionsImplForDebugger" AfterTargets="AfterBuild" Condition="Exists('$(_TinyCLRCollectionsImplSource)')">
    <Copy SourceFiles="$(_TinyCLRCollectionsImplSource)" DestinationFiles="$(OutDir)pe\GHIElectronics.TinyCLR.Collections.dll" OverwriteReadOnlyFiles="true" SkipUnchangedFiles="false" />
  </Target>
</Project>
