<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="15.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup>
    <MSBuildAllProjects>$(MSBuildAllProjects);$(MSBuildThisFileFullPath)</MSBuildAllProjects>
    <_TinyCLRCanImplSource>$(MSBuildThisFileDirectory)..\..\lib\net48\GHIElectronics.TinyCLR.Devices.Can.dll</_TinyCLRCanImplSource>
  </PropertyGroup>
  <Target Name="CopyTinyCLRCanImplForDebugger" AfterTargets="AfterBuild" Condition="Exists('$(_TinyCLRCanImplSource)')">
    <Copy SourceFiles="$(_TinyCLRCanImplSource)" DestinationFiles="$(OutDir)pe\GHIElectronics.TinyCLR.Devices.Can.dll" OverwriteReadOnlyFiles="true" SkipUnchangedFiles="false" />
  </Target>
</Project>
