<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="15.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <ItemGroup>
    <Reference Include="GHIElectronics.TinyCLR.Devices.Pwm">
      <HintPath>$(MSBuildThisFileDirectory)..\..\lib\net48\GHIElectronics.TinyCLR.Devices.Pwm.dll</HintPath>
      <Private>False</Private>
    </Reference>
  </ItemGroup>
  <PropertyGroup>
    <MSBuildAllProjects>$(MSBuildAllProjects);$(MSBuildThisFileFullPath)</MSBuildAllProjects>
    <_TinyCLRPwmShimSource>$(MSBuildThisFileDirectory)..\..\desktop-shim\GHIElectronics.TinyCLR.Devices.Pwm.dll</_TinyCLRPwmShimSource>
    <_TinyCLRPwmImplSource>$(MSBuildThisFileDirectory)..\..\tinyclr\GHIElectronics.TinyCLR.Devices.Pwm.dll</_TinyCLRPwmImplSource>
  </PropertyGroup>
  <Target Name="CopyTinyCLRPwmDesktopShim" AfterTargets="AfterBuild" Condition="Exists('$(_TinyCLRPwmShimSource)')">
    <Copy SourceFiles="$(_TinyCLRPwmShimSource)"
          DestinationFiles="$(OutDir)GHIElectronics.TinyCLR.Devices.Pwm.dll"
          OverwriteReadOnlyFiles="true"
          SkipUnchangedFiles="false" />
  </Target>
  <Target Name="CopyTinyCLRPwmImplForDebugger" AfterTargets="AfterBuild" Condition="Exists('$(_TinyCLRPwmImplSource)')">
    <Copy SourceFiles="$(_TinyCLRPwmImplSource)"
          DestinationFiles="$(OutDir)pe\GHIElectronics.TinyCLR.Devices.Pwm.dll"
          OverwriteReadOnlyFiles="true"
          SkipUnchangedFiles="false" />
  </Target>
</Project>
