<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="15.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <ItemGroup>
    <Reference Include="GHIElectronics.TinyCLR.IO.TinyFileSystem">
      <HintPath>$(MSBuildThisFileDirectory)..\..\lib\net48\GHIElectronics.TinyCLR.IO.TinyFileSystem.dll</HintPath>
      <Private>False</Private>
    </Reference>
  </ItemGroup>
  <PropertyGroup>
    <MSBuildAllProjects>$(MSBuildAllProjects);$(MSBuildThisFileFullPath)</MSBuildAllProjects>
    <_TinyCLRTfsImplSource>$(MSBuildThisFileDirectory)..\..\lib\net48\GHIElectronics.TinyCLR.IO.TinyFileSystem.dll</_TinyCLRTfsImplSource>
  </PropertyGroup>
  <Target Name="CopyTinyCLRTfsImplForDebugger" AfterTargets="AfterBuild" Condition="Exists('$(_TinyCLRTfsImplSource)')">
    <Copy SourceFiles="$(_TinyCLRTfsImplSource)" DestinationFiles="$(OutDir)pe\GHIElectronics.TinyCLR.IO.TinyFileSystem.dll" OverwriteReadOnlyFiles="true" SkipUnchangedFiles="false" />
  </Target>
</Project>
