<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="15.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <ItemGroup>
    <Reference Include="GHIElectronics.TinyCLR.Devices.Onewire" Condition="Exists('$(MSBuildProjectDirectory)\packages.config')">
      <HintPath>$(MSBuildThisFileDirectory)..\..\lib\net48\GHIElectronics.TinyCLR.Devices.Onewire.dll</HintPath>
      <Private>False</Private>
    </Reference>
  </ItemGroup>
  <PropertyGroup>
    <MSBuildAllProjects>$(MSBuildAllProjects);$(MSBuildThisFileFullPath)</MSBuildAllProjects>
    <_TinyCLROnewireShimSource>$(MSBuildThisFileDirectory)..\..\desktop-shim\GHIElectronics.TinyCLR.Devices.Onewire.dll</_TinyCLROnewireShimSource>
    <_TinyCLROnewireImplSource>$(MSBuildThisFileDirectory)..\..\tinyclr\GHIElectronics.TinyCLR.Devices.Onewire.dll</_TinyCLROnewireImplSource>
  </PropertyGroup>
  <Target Name="CopyTinyCLROnewireDesktopShim" AfterTargets="AfterBuild" Condition="Exists('$(_TinyCLROnewireShimSource)')">
    <Copy SourceFiles="$(_TinyCLROnewireShimSource)"
          DestinationFiles="$(OutDir)GHIElectronics.TinyCLR.Devices.Onewire.dll"
          OverwriteReadOnlyFiles="true"
          SkipUnchangedFiles="false" />
  </Target>
  <Target Name="CopyTinyCLROnewireImplForDebugger" AfterTargets="AfterBuild" Condition="Exists('$(_TinyCLROnewireImplSource)')">
    <Copy SourceFiles="$(_TinyCLROnewireImplSource)"
          DestinationFiles="$(OutDir)pe\GHIElectronics.TinyCLR.Devices.Onewire.dll"
          OverwriteReadOnlyFiles="true"
          SkipUnchangedFiles="false" />
  </Target>
</Project>
