<?xml version="1.0" encoding="utf-8"?>

<!-- Consumer-side props imported by user projects via the NuGet package
     mechanism. See the Networking / Native equivalents for full rationale. -->
<Project ToolsVersion="15.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <ItemGroup>
    <Reference Include="GHIElectronics.TinyCLR.Devices.Gpio" Condition="Exists('$(MSBuildProjectDirectory)\packages.config')">
      <HintPath>$(MSBuildThisFileDirectory)..\..\lib\net48\GHIElectronics.TinyCLR.Devices.Gpio.dll</HintPath>
      <Private>False</Private>
    </Reference>
  </ItemGroup>
  <PropertyGroup>
    <MSBuildAllProjects>$(MSBuildAllProjects);$(MSBuildThisFileFullPath)</MSBuildAllProjects>
    <_TinyCLRGpioShimSource>$(MSBuildThisFileDirectory)..\..\desktop-shim\GHIElectronics.TinyCLR.Devices.Gpio.dll</_TinyCLRGpioShimSource>
    <_TinyCLRGpioImplSource>$(MSBuildThisFileDirectory)..\..\tinyclr\GHIElectronics.TinyCLR.Devices.Gpio.dll</_TinyCLRGpioImplSource>
    <_SystemDeviceGpioShimSource>$(MSBuildThisFileDirectory)..\..\desktop-shim\System.Device.Gpio.dll</_SystemDeviceGpioShimSource>
    <_SystemDeviceGpioImplSource>$(MSBuildThisFileDirectory)..\..\tinyclr\System.Device.Gpio.dll</_SystemDeviceGpioImplSource>
  </PropertyGroup>
  <Target Name="CopyTinyCLRGpioDesktopShim" AfterTargets="AfterBuild" Condition="Exists('$(_TinyCLRGpioShimSource)')">
    <Copy SourceFiles="$(_TinyCLRGpioShimSource)" DestinationFiles="$(OutDir)GHIElectronics.TinyCLR.Devices.Gpio.dll" OverwriteReadOnlyFiles="true" SkipUnchangedFiles="false" />
  </Target>
  <Target Name="CopyTinyCLRGpioImplForDebugger" AfterTargets="AfterBuild" Condition="Exists('$(_TinyCLRGpioImplSource)')">
    <Copy SourceFiles="$(_TinyCLRGpioImplSource)" DestinationFiles="$(OutDir)pe\GHIElectronics.TinyCLR.Devices.Gpio.dll" OverwriteReadOnlyFiles="true" SkipUnchangedFiles="false" />
  </Target>
  <Target Name="CopySystemDeviceGpioDesktopShim" AfterTargets="AfterBuild" Condition="Exists('$(_SystemDeviceGpioShimSource)')">
    <Copy SourceFiles="$(_SystemDeviceGpioShimSource)" DestinationFiles="$(OutDir)System.Device.Gpio.dll" OverwriteReadOnlyFiles="true" SkipUnchangedFiles="false" />
  </Target>
  <Target Name="CopySystemDeviceGpioImplForDebugger" AfterTargets="AfterBuild" Condition="Exists('$(_SystemDeviceGpioImplSource)')">
    <Copy SourceFiles="$(_SystemDeviceGpioImplSource)" DestinationFiles="$(OutDir)pe\System.Device.Gpio.dll" OverwriteReadOnlyFiles="true" SkipUnchangedFiles="false" />
  </Target>
</Project>
