//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GHIElectronics.TinyCLR.UI
{
    
    internal partial class Resources
    {
        private static System.Resources.ResourceManager manager;
        internal static System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if ((Resources.manager == null))
                {
                    Resources.manager = new System.Resources.ResourceManager("GHIElectronics.TinyCLR.UI.Resources", typeof(Resources).Assembly);
                }
                return Resources.manager;
            }
        }
        internal static System.Drawing.Bitmap GetBitmap(Resources.BitmapResources id)
        {
            return ((System.Drawing.Bitmap)(ResourceManager.GetObject(((short)(id)))));
        }
        [System.SerializableAttribute()]
        internal enum BitmapResources : short
        {
            DropdownButton_Down = -31110,
            Button_Down = -18532,
            Keyboard_Numbers = -14062,
            Button_Up = -12892,
            ProgressBar_Fill = -12135,
            Modal = -11358,
            Keyboard_Lowercase = -10522,
            RadioButton = 1102,
            Keyboard_Symbols = 1558,
            DropdownText_Up = 1846,
            DropdownButton_Up = 4119,
            DropdownText_Down = 13519,
            ProgressBar = 15350,
            Keyboard_Uppercase = 21332,
            CheckBox_Off = 23409,
            CheckBox_On = 27788,
        }
    }
}
