<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="15.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup>
    <MSBuildAllProjects>$(MSBuildAllProjects);$(MSBuildThisFileFullPath)</MSBuildAllProjects>
    <_TinyCLRUsbClientImplSource>$(MSBuildThisFileDirectory)..\..\lib\net48\GHIElectronics.TinyCLR.Devices.UsbClient.dll</_TinyCLRUsbClientImplSource>
  </PropertyGroup>
  <Target Name="CopyTinyCLRUsbClientImplForDebugger" AfterTargets="AfterBuild" Condition="Exists('$(_TinyCLRUsbClientImplSource)')">
    <Copy SourceFiles="$(_TinyCLRUsbClientImplSource)" DestinationFiles="$(OutDir)pe\GHIElectronics.TinyCLR.Devices.UsbClient.dll" OverwriteReadOnlyFiles="true" SkipUnchangedFiles="false" />
  </Target>
</Project>
