<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="15.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <ItemGroup>
    <Reference Include="GHIElectronics.TinyCLR.IO" Condition="'$(NuGetProjectStyle)' != 'PackageReference'">
      <HintPath>$(MSBuildThisFileDirectory)..\..\lib\net48\GHIElectronics.TinyCLR.IO.dll</HintPath>
      <Private>False</Private>
    </Reference>
  </ItemGroup>
  <PropertyGroup>
    <MSBuildAllProjects>$(MSBuildAllProjects);$(MSBuildThisFileFullPath)</MSBuildAllProjects>
    <_TinyCLRIOShimSource>$(MSBuildThisFileDirectory)..\..\desktop-shim\GHIElectronics.TinyCLR.IO.dll</_TinyCLRIOShimSource>
    <_TinyCLRIOImplSource>$(MSBuildThisFileDirectory)..\..\tinyclr\GHIElectronics.TinyCLR.IO.dll</_TinyCLRIOImplSource>
  </PropertyGroup>
  <Target Name="CopyTinyCLRIODesktopShim" AfterTargets="AfterBuild" Condition="Exists('$(_TinyCLRIOShimSource)')">
    <Copy SourceFiles="$(_TinyCLRIOShimSource)" DestinationFiles="$(OutDir)GHIElectronics.TinyCLR.IO.dll" OverwriteReadOnlyFiles="true" SkipUnchangedFiles="false" />
  </Target>
  <Target Name="CopyTinyCLRIOImplForDebugger" AfterTargets="AfterBuild" Condition="Exists('$(_TinyCLRIOImplSource)')">
    <Copy SourceFiles="$(_TinyCLRIOImplSource)" DestinationFiles="$(OutDir)pe\GHIElectronics.TinyCLR.IO.dll" OverwriteReadOnlyFiles="true" SkipUnchangedFiles="false" />
  </Target>
</Project>
