<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="15.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <ItemGroup>
    <Reference Include="GHIElectronics.TinyCLR.Data.Json">
      <HintPath>$(MSBuildThisFileDirectory)..\..\lib\net48\GHIElectronics.TinyCLR.Data.Json.dll</HintPath>
      <Private>False</Private>
    </Reference>
  </ItemGroup>
  <PropertyGroup>
    <MSBuildAllProjects>$(MSBuildAllProjects);$(MSBuildThisFileFullPath)</MSBuildAllProjects>
    <_TinyCLRDataJsonImplSource>$(MSBuildThisFileDirectory)..\..\lib\net48\GHIElectronics.TinyCLR.Data.Json.dll</_TinyCLRDataJsonImplSource>
  </PropertyGroup>
  <Target Name="CopyTinyCLRDataJsonImplForDebugger" AfterTargets="AfterBuild" Condition="Exists('$(_TinyCLRDataJsonImplSource)')">
    <Copy SourceFiles="$(_TinyCLRDataJsonImplSource)" DestinationFiles="$(OutDir)pe\GHIElectronics.TinyCLR.Data.Json.dll" OverwriteReadOnlyFiles="true" SkipUnchangedFiles="false" />
  </Target>
</Project>
