<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="15.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup>
    <MSBuildAllProjects>$(MSBuildAllProjects);$(MSBuildThisFileFullPath)</MSBuildAllProjects>
    <_TinyCLRLinqImplSource>$(MSBuildThisFileDirectory)..\..\lib\net48\GHIElectronics.TinyCLR.Linq.dll</_TinyCLRLinqImplSource>
  </PropertyGroup>
  <Target Name="CopyTinyCLRLinqImplForDebugger" AfterTargets="AfterBuild" Condition="Exists('$(_TinyCLRLinqImplSource)')">
    <Copy SourceFiles="$(_TinyCLRLinqImplSource)" DestinationFiles="$(OutDir)pe\GHIElectronics.TinyCLR.Linq.dll" OverwriteReadOnlyFiles="true" SkipUnchangedFiles="false" />
  </Target>
</Project>
